### ISSUE TITLE
Kanban

### ISSUE THREAD

**Issue by shakerAbuDrais** [Mhamad-Raad/final-capstone-frontend#12]
### _Hey reviewer 👋_

We have created a Kanban board and added all the tasks with the same time load for all the developers in the project.
We are going to develop our _Final Capstone_ project in two repositories. We are a team of three developers

1- @KanzaTahreem 
2- @Mhamad-Raad 
3- @shakerAbuDrais 

### _Repositories 🔗_
 _To handle frontend UI 👉_ [final capstone frontend](https://github.com/Mhamad-Raad/final-capstone-frontend) 
 _To handle backend API 👉_ [final capstone backend](https://github.com/Mhamad-Raad/final-capstone-backend)

### _Kanban boards 🔗_ 
 _To handle backend API 👉_  [Back-End Kanban board](https://github.com/users/Mhamad-Raad/projects/7)
 _To handle frontend UI 👉_ [Front-End Kanban board](https://github.com/users/Mhamad-Raad/projects/6)

### _Initial state of Kanban boards_

<details>
  <summary>Frontend Kanban board</summary>
  
![frontend](https://user-images.githubusercontent.com/106119105/220791936-d57d4c18-2707-48bf-8354-f1678dede19a.PNG)
</details>

<details>
  <summary>Backend Kanban board</summary>
  
![backend](https://user-images.githubusercontent.com/106119105/220791991-eac8b48f-051e-4fd5-9cf2-8157d570ae12.PNG)
</details>

**_PS: Issue for review created in front end repository_**

**Happy reviewing!** 💻

**Comment by Meltrust** [comment]
Hi @shakerAbuDrais,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the initial state of your kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  

## Highlights
- You did a great job distributing the tasks equitably
- Your tasks' descriptions were detailed


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
